# apiVersion: eksctl.io/v1alpha5
# kind: ClusterConfig

# metadata:
#   name: cr-frntnd-cluster
#   region: ca-central-1

# managedNodeGroups:
# - name: general
#   instanceType: t2.small
#   minSize: 3
#   maxSize: 6
#   spot: true

---
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: cr-cluster
  region: ca-central-1

managedNodeGroups:
- name: on-demand
  labels:
    role: on-demand
  instanceType: t3.micro
  desiredCapacity: 2
  spot: true