apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: nginx-webapp
  name: nginx-webapp
  namespace: frontend-namespace
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx-webapp
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nginx-webapp
    spec:
      containers:
      - image: DOCKER_IMAGE
        name: webapp
        imagePullPolicy: Always
        resources: {}
        ports:
          - containerPort: 8080
status: {}

---

apiVersion: v1
kind: Service
metadata:
  name: nginx-webapp
  namespace: frontend-namespace
  labels:
    run: nginx-webapp
spec:
  ports:
  - name: nginxport
    nodePort: 3000
  - port: 8080
    protocol: TCP
  selector:
    app: nginx-webapp
  type: LoadBalancer