name: Deploy to Lambda

on:
  push:
    branches:
      - web-app
    paths:
      - 'backend'


jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9' # Specify the Python version you need

      # - name: Install dependencies
      #   run: pip install -r requirements.txt # If you have dependencies in requirements.txt

      - name: Create deployment package
        run: |
          zip -r deployment_package.zip *.py

      - name: Deploy to Lambda
        uses: einaregilsson/lambda-deploy@v1
        with:
          function-name: your-lambda-function-name
          package: deployment_package.zip
          region: your-aws-region
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}